apiVersion: v1
kind: Service
metadata:
  name: {{ include "questify-garage.fullname" . }}
  labels:
    {{- include "questify-garage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: s3
      port: {{ .Values.service.s3Port }}
      targetPort: s3
      protocol: TCP
      {{- if .Values.service.s3NodePort }}
      nodePort: {{ .Values.service.s3NodePort }}
      {{- end }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "questify-garage.selectorLabels" . | nindent 4 }}
