apiVersion: v2
name: questify
description: Umbrella Helm chart for Questify application
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - questify
  - todo
  - gamification

home: https://github.com/axelfrache/questify
sources:
  - https://github.com/axelfrache/questify

maintainers:
  - name: Axel Frache
    url: https://github.com/axelfrache
