global:
  imageRegistry: "registry.axelfrache.me"
  imagePullSecrets: []
  storageClass: "longhorn"

namespace:
  name: questify
  create: true

ingress:
  enabled: true
  className: nginx
  host: app.getquestify.com
  tls:
    enabled: false
    secretName: questify-tls

statefulNodeAffinity:
  nodeSelector:
    kubernetes.io/hostname: talos-worker
