apiVersion: v2
name: questify-auth-service
description: Questify Authentication Service
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - questify
  - auth
  - authentication
  - spring-boot

maintainers:
  - name: Axel Frache
    url: https://github.com/axelfrache
