apiVersion: v2
name: questify-project-service
description: Questify Project Service
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - questify
  - project
  - spring-boot

maintainers:
  - name: Axel Frache
    url: https://github.com/axelfrache
