---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: questify
spec:
  encryptedData:
    .dockerconfigjson: AgAC9kXIWkvo1605Bs2Wz1qnAPcGS4iytUAGQjy6iDvdyDwxJko9xjE1aFWK4iahC2hHxsRU8bAvS8ojG95qzWd/E6IDvyGolQlUT+L2JZ06m7Bnhj4IuxRSWbexmGRmwgYPWK9oCkgj149dC/VrF9KgdbdhaLYWoxI05Qq0z6YG2rrqmC4AL/+SwTdHEpfkhZqqxNWdEkoOdQV4Hnemgc92QA7PmLo2aVTBBxcf7ScyfLmCL/BceO7Xe9x3zkA+EVUowCWJpJ1Xz6JDCVMdaLoEWL8L0VptwD3KwccrEUTvvbKMpG5DdJBbzWe1WgiRDt9dUxdpEL+bQBynABvSAmi80wvpKqcEbWoAVzLHF6YpXAy5uc/6ma36SUaW88sw6RNJxQru+MHSAoJtaKKycd10zX3LcP1MClkVHkLZWu2Jo5roh2QLtV3MaPJygKthOTnVbIIYMF9ijnX8BKJoa9mMSuVTAAZiStdYzuKfMrR1wAPj6B7hspsIYlOcPEPDtpmGpErvoHH7p4j7eUbNDHVRtZp2MhLIDLoWa/h4zmTo9wxVwmfFHVJ5dSN1/F30deQS1Q3WROVcLijteKHMW7cPBnDthXKPKXwsaj3+4InKdFgG6mUJZVXbKsZY2WcqzAJLJX7gN8S2b83qKbM5dPIaYgfyYLJEn/YYALAi7tjAl77ZZuhgzy5pkfKMNThR7AgRoFBORzHuZQQmVmcmjRHpEF8xc6c+98ihSAzDyi1pwq6a01vPFlNsghOqYkg0UG/OGZD7Wn5IjJI8PCgE1uhhMjcm5PFxWSLmQSKqrb21jqZ2mQkk6gOzXozrc8p+WGE/vMSOdsZsrRLzBtGyHPLemGaxi1ZL0UoUP50O9hbOJfn4qV1Tln5+krRAa5E/f/jmfumk5CsOg1GuPLVU2dpny3Nqpy5q4HHtkgKNFbHiMhjl8rs=
  template:
    metadata:
      name: regcred
      namespace: questify
    type: kubernetes.io/dockerconfigjson
