---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: questify
spec:
  encryptedData:
    .dockerconfigjson: AgAmDus6+fsL59QBkrvOoMU9j3pWw8Llrc2xG9cV2rudF3Ch2HMGYLM727721POb3ym1c7XoOwxvL7//fPVHg7YIFoGqdU/86arukBRf0fyN4/9ssSXmLYXnpdEM+liFskgLcxhQ2kv6jjj9jDIqwIOI9vnbGWu9GgoEOD7gpee+6ZtFp9R52tedBYst0Ghwdk8p8miPuDIp3UGnBzH35x9wNbVv1kTxVMSE5xRFkiRJcARjnF7ipm/4wUpRd04Tsu40acj6cO8uvgqEOR9yXd3voz5vBnM05KJOGynBFE+mMdqvA2MCn9ql72TBExcfimy5LOf5iyQRYVrqw6j/uCtGba96o8LIPjVmbmAl8l6h1dK93feK1GPQbHH2BYm36nAGfGa2hqUXF2HDir/nbbqoHWplilso4TvMYjy+hhW8sTBfoiQ6c0tThJAWuDSfROvGpNtKljlfNPt+oFreYenK56ab7UnQ9h4s0bzt5m3VPlNCM7PnQLw886g8mW7CLplS4ZC1DR/5BnTWimi1+34+pOLenrX2EKK9Eb4KtpxhwjOqHMPRAVQaiDGZdgBzoVXpRkGXNuUhJXD1pIkuIJ+qq1x7ZlBcN/z6esbg+zlekbXSloVEoGGiofJQO8xpS+4U0DBYNThxNbDXVloCXXuruB6mvrNfPLEsLWGuPkKTJ1lXUf/y4oC9jrgIKyd8v6BLqMr8+9ybinaZHB81KmzHEtvaM8yV22MZvvzzW0CjGg2F9jVubLDff8UfZQpCoKxm9+PgRnjaN2S8igdeS31NOPVA7YT6Q4ws51kcz7nW0l2bPs22dLg7U/Y935nWqjxHoKVcvW6KJ1FjtPtCy9zx0TZKyMBgApZvANjwsog4bx8lwK12A8gnbJatSErMgdQ9kIcVr1tkamatl3guQd6IW+1PUWWii0mjtD08ndQrdYrCnZgQ0/CtOvC0SjBwgqF2vfPWI50p6aE=
  template:
    metadata:
      name: regcred
      namespace: questify
    type: kubernetes.io/dockerconfigjson
