image:
  repository: registry.axelfrache.me/questify/backend
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

replicaCount: 1

serviceAccount:
  create: true
  annotations: {}
  name: ""

spring:
  profile: production
  jpa:
    ddlAuto: update

database:
  host: questify-postgresql
  port: 5432
  name: questify
  existingSecret: questify-postgresql
  secretKeys:
    usernameKey: username
    passwordKey: password

s3:
  endpoint: http://questify-minio:9000
  publicUrl: https://s3.getquestify.com
  bucket: questify-profiles
  region: us-east-1
  existingSecret: questify-minio
  secretKeys:
    accessKeyKey: root-user
    secretKeyKey: root-password

jwt:
  accessExpiration: "900000"
  refreshExpiration: "604800000"
  secret: ""
  existingSecret: "questify-backend-jwt"
  secretKey: jwt-secret

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: app.getquestify.com
  path: /api
  pathType: Prefix
  tls: []

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}
