{{- if not .Values.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "questify-backend.fullname" . }}-jwt
  labels:
    {{- include "questify-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.jwt.secretKey }}: {{ .Values.jwt.secret | b64enc | quote }}
{{- end }}
